title: Opeyemi Fikunyi Aransiola
logo: Data.jpeg
description: i'm a data analyst with experience in automating reports using Advance Excel, data integeration and manipulation in SQL and creating insightful visualizations in PowerBI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
